apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: sh
spec:
  containers:
  - name: embedway
    image: centos_net
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
