apiVersion: v1                      #核心API
kind: ReplicationController         #副本控制器RC
metadata:
  name: mysql                       #RC的名称，全局唯一
spec:
  replicas: 1                       #Pod副本的期待数量
  selector:
    app: mysql                      #监控和管理拥有mysql标签的Pod
  template:
    metadata:
      labels:
        app: mysql                  #Pod的标签，必须与RC的selector一致
    spec:
      containers:                   #Pod内容器的定义部分
      - name: mysql                 #容器名
        image: mysql                #镜像名
        imagePullPolicy: IfNotPresent       #本地有该镜像，就不去拉取
        ports:
        - containerPort: 3306       #容器应用监听的端口
        env:
        - name: MYSQL_ROOT_PASSWORD #注入容器内的环境变量
          value: "123456"

