cluster.name: elasticsearch_cluster
node.name: lance-pad
node.master: false
node.data: true
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
bootstrap.mlockall: true
network.host: 0.0.0.0
network.publish_host: 10.40.0.68
transport.tcp.port: 9300
http.port: 9200
index.refresh_interval: 5s
script.inline: true
script.indexed: true

discovery.zen.ping.timeout: 100s
discovery.zen.fd.ping_timeout: 100s
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["10.40.0.67:9300", "10.40.0.66:9300", "10.40.0.68:9300"]
discovery.zen.minimum_master_nodes: 2
gateway.recover_after_nodes: 2
