apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-conf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/embedway_virtionet
spec:
  config: '{
  "cniVersion": "0.3.1",
  "type": "host-device",
  "name": "host-device-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.66.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.66.217.1"
  }
}'
