apiVersion: v1
kind: Pod
metadata:
  name: virtiopod1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: host-device-conf
spec:
  containers:
  - image: centos/tools
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    imagePullPolicy: IfNotPresent
    name: centos1
    securityContext:
      capabilities:
        drop:
        - ALL
        add: ["NET_ADMIN", "NET_RAW"]
    resources:
      requests:
        intel.com/embedway_virtionet: '1'
      limits:
        intel.com/embedway_virtionet: '1'
  restartPolicy: Always

